### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by ianhattendorf** [gantsign/ansible-role-intellij#163]
Are there any plans to support Python 3? Currently, we need to run the role like so to override the preferred `ansible_python_interpreter`:

```yaml
  roles:
    - { role: gantsign.intellij, ansible_python_interpreter: /usr/bin/python2 }
```

It looks like most of the issues are due to treating `bytes` as `str` in `intellij_configure_jdk.py`:

- `AttributeError: 'bytes' object has no attribute 'seek'`
- `TypeError: endswith first arg must be bytes or a tuple of bytes, not str`

**Comment by freemanjp** [comment]
@ianhattendorf thanks for the feedback, the fix for the issue you reported can be found in the [4.1.0](https://github.com/gantsign/ansible-role-intellij/releases/tag/4.1.0) release of this role.

While I was running tests for Python 3, it seems only the Testinfra tests were running on Python 3, the actual role was still running on 2.7. I've fixed the code and the tests, so hopefully the Python 3 support should be fixed and stay fixed.

**Comment by ianhattendorf** [comment]
Great, thanks for the fast response and the great role. Everything is working now :+1:
