### ISSUE TITLE
Looking for correct name for "Save Actions" plugin

### ISSUE THREAD

**Issue by btomasini** [gantsign/ansible-role-intellij#98]
I am trying to install the following plugin via this role, and am encoutering a error saying it cannot be found. 

https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/META-INF/plugin.xml

What is the proper name for the list of intellij plugins?  I have tried 

- Save Actions
- "Save Actions"
- save actions
- save_actions

**Comment by freemanjp** [comment]
@btomasini, you need to specify the plugin ID rather than the plugin name (i.e. `com.dubreuia` in this case); however, since the Save Actions plugin is distributed as a JAR rather than a ZIP file it's not currently working with this role. I expect to have a fix for JAR support sometime today.

Thanks for the feedback.

FYI: I find the following command useful for finding plugins:
```bash
cat ~/.IntelliJIdea2017.1/config/plugins/availables.xml | xmlstarlet sel -I -t -e plugins -m //idea-plugin -e plugin -a 'id' -v 'id' -b -a 'name' -v 'name' -b | less
```
For the community edition use:
```bash
cat ~/.IdeaIC2017.1/config/plugins/availables.xml | xmlstarlet sel -I -t -e plugins -m //idea-plugin -e plugin -a 'id' -v 'id' -b -a 'name' -v 'name' -b | less
```

**Comment by freemanjp** [comment]
@btomasini the Save Actions plugin (`com.dubreuia`) should work with version 2.10.1 of this role.
